stages:
  - deploy
  - validate

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:2.x
    entrypoint: [""]
  variables:
    AWS_ACCESS_KEY_ID: AKIA2VAGTNBZFH4B6TOD
    AWS_SECRET_ACCESS_KEY: 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
    AWS_DEFAULT_REGION: ap-south-1
  script:
    - aws cloudformation deploy --template-file cloudformation/ec2-instance.yaml --stack-name MyEC2Stack --capabilities CAPABILITY_IAM

validate:
  stage: validate
  image:
    name: amazon/aws-cli:2.x
    entrypoint: [""]
  variables:
    AWS_ACCESS_KEY_ID: AKIA2VAGTNBZFH4B6TOD
    AWS_SECRET_ACCESS_KEY: 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
    AWS_DEFAULT_REGION: ap-south-1
  script:
    - aws cloudformation validate-template --template-body file://cloudformation/ec2-instance.yaml
