stages:
  - deploy
  - validate

before_script:
  - apt-get update && apt-get install -y unzip
  - curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install


deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:2.x
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - aws cloudformation deploy --template-file vpc-bastian-ec2.yaml --stack-name ec2-bastian --capabilities CAPABILITY_IAM --disable-rollback

validate:
  stage: validate
  image:
    name: amazon/aws-cli:2.x
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - aws cloudformation validate-template --template-body file://vpc-bastian-ec2.yaml --disable-rollback
