AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SamVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  SamSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SamVPC
      CidrBlock: 10.0.0.0/24

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06ca3ca175f37dd66
      InstanceType: t2.micro
      KeyName: sam-key
      VpcId: !Ref SamVPC
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SamSubnet
