AWSTemplateFormatVersion: "2010-09-09"

Resources:
  FailedChangeSet1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName1*

  FailedChangeSet2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType

  FailedChangeSet3:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: InvalidEmailAddress
          Protocol: InvalidProtocol

  FailedChangeSet4:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName2*

  FailedChangeSet5:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType

  FailedChangeSet6:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: InvalidEmailAddress
          Protocol: InvalidProtocol

  FailedChangeSet7:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName3*

  FailedChangeSet8:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType

  FailedChangeSet9:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: InvalidEmailAddress
          Protocol: InvalidProtocol

  FailedChangeSet10:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName4*

  FailedChangeSet11:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType

  FailedChangeSet12:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: InvalidEmailAddress
          Protocol: InvalidProtocol

  FailedChangeSet13:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName5*

  FailedChangeSet14:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType

  FailedChangeSet15:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: InvalidEmailAddress
          Protocol: InvalidProtocol

  FailedChangeSet16:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName6*

  FailedChangeSet17:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType

  FailedChangeSet18:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: InvalidEmailAddress
          Protocol: InvalidProtocol

  FailedChangeSet19:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName7*

  FailedChangeSet20:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType
