AWSTemplateFormatVersion: "2010-09-09"

Resources:
  FailedChangeSet1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: InvalidBucketName1*

  FailedChangeSet2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: InvalidInstanceType

  FailedChangeSet3:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: InvalidEmailAddress
          Protocol: InvalidProtocol
